# Generated by Django 4.2.13 on 2024-05-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longUrl', models.URLField(max_length=20, verbose_name='Short URL')),
            ],
        ),
    ]
